### ISSUE TITLE
Waystone labels remains after breaking waystone

### ISSUE THREAD

**Issue by JWTHDYTWA** [Rikshy/AntiqueAtlasExtras#8] opened 2019-06-20 11:36 UTC
Atlas labels generated by waystones remains when waystone the label belong to is being broken.

**Comment by Rikshy** [comment] 2019-07-01 09:08
Waystones from the Waystone mod or the Signpost mod?

**Comment by JWTHDYTWA** [comment] 2019-07-01 09:10
Both of them.

**Comment by Rikshy** [comment] 2019-07-01 09:14
This is wierd, I just tested it in my dev environment and it works :S

**Comment by Rikshy** [comment] 2019-07-01 09:40
which version of Waystones and Signpost mod are you using?

**Comment by JWTHDYTWA** [comment] 2019-07-01 09:42
Atlas Extras: 1.6
Waystones: 4.0.67
Signpost: 1.08.2

**Comment by Rikshy** [comment] 2019-07-01 11:06
Are you on a server or sp?

**Comment by JWTHDYTWA** [comment] 2019-07-02 15:31
Singleplayer. But on modpack

**Comment by Rikshy** [comment] 2020-04-18 09:51
Issue with the main mod: https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/262

**Comment by Rikshy** [comment] 2020-04-18 09:52
Duplicate of #11

**Closed as completed by Rikshy** 2020-04-18 09:52 UTC
